### PR TITLE
Allow initializing a Coqpit object directly from argparse

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by reuben** [comment]
@erogol ping

**Comment by erogol** [comment]
@reuben  Looks good to me. Just wondering what was the use-case in STT? 
Can you maybe add an example to the README.md too just to inform the potential user?

**Comment by reuben** [comment]
The use-case is being able to do validation with required fields in `__post_init__` while using argparse input. Without this PR you have to create the object, which forces you to specify all required fields, and runs `__post_init__`, and only then can you call `parse_args`, which /doesn't/ call `__post_init__`, forcing you to call it by hand. This turns all of this into a single `ConfigClass.init_from_argparse()` call.

**Comment by reuben** [comment]
I'll add an example to the README.

**Pull request merged**
